/**
 * Fog of war — information visibility (§5, §6).
 *
 * Three levels per foreign army:
 *   HIDDEN  — not detected; no marker.
 *   CONTACT — inside a friendly unit's OUTER vision: position known, but not
 *             composition. Rendered as an unknown-contact marker ("?").
 *   VISIBLE — inside a friendly unit's INNER vision: full composition revealed.
 *
 * Vision is generated by friendly army stacks (per-unit outer/inner radii from
 * the unit catalogue, best unit in the stack wins) and, more weakly, by owned
 * province centres. Own armies are always VISIBLE. With fog disabled
 * (sandbox / `fogOfWar === false`) everything is VISIBLE.
 *
 * Pure and cheap: O(foreignArmies × visionSources). Recomputed on the sim
 * cadence, not per render frame.
 */

import type { GameState } from './game-state';
import type { WorldData } from './world-data';
import { strongestGroup } from './units/army';
import { unitType } from './units/unit-catalog';
import { wrappedDistanceSq } from './geometry';

export type ContactLevel = 'hidden' | 'contact' | 'visible';

/** Outer-vision radius a friendly province centre projects (no inner reveal). */
const PROVINCE_VISION_OUTER = 130;

interface VisionSource {
  x: number;
  z: number;
  outerSq: number;
  innerSq: number;
}

function friendlyVisionSources(state: GameState, world: WorldData): VisionSource[] {
  const player = state.playerCountryId;
  const sources: VisionSource[] = [];
  for (const army of Object.values(state.armies)) {
    if (army.ownerCountryId !== player) continue;
    const lead = strongestGroup(army);
    const outer = lead ? unitType(lead.typeId).visionOuter : 150;
    const inner = lead ? unitType(lead.typeId).visionInner : 80;
    sources.push({ x: army.x, z: army.z, outerSq: outer * outer, innerSq: inner * inner });
  }
  for (const province of world.provinces) {
    if (state.provinceOwners[province.id] !== player) continue;
    sources.push({
      x: province.center[0],
      z: province.center[1],
      outerSq: PROVINCE_VISION_OUTER * PROVINCE_VISION_OUTER,
      innerSq: 0,
    });
  }
  return sources;
}

export function computeArmyVisibility(
  state: GameState, world: WorldData,
): Map<string, ContactLevel> {
  const result = new Map<string, ContactLevel>();
  const player = state.playerCountryId;

  if (!state.fogOfWar) {
    for (const id of Object.keys(state.armies)) result.set(id, 'visible');
    return result;
  }

  const sources = friendlyVisionSources(state, world);
  for (const army of Object.values(state.armies)) {
    if (army.ownerCountryId === player) {
      result.set(army.id, 'visible');
      continue;
    }
    let level: ContactLevel = 'hidden';
    for (const source of sources) {
      const distSq = wrappedDistanceSq(source.x, source.z, army.x, army.z, world.width);
      if (distSq <= source.innerSq) { level = 'visible'; break; }
      if (distSq <= source.outerSq) level = 'contact';
    }
    result.set(army.id, level);
  }
  return result;
}

/** True when the player may see any detail of `countryId`'s internal state
 *  (economy, production, buildings). Own country, or fog disabled. */
export function foreignDetailVisible(state: GameState, countryId: number): boolean {
  return countryId === state.playerCountryId || !state.fogOfWar;
}
